version: 0.0
os: linux
files:
  - source: /app.js
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_nodejs_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_nodejs_server
      timeout: 300
      runas: root
